routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::middleware(['auth'])->group(function(){
    // home
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    // booking
    Route::resource('/booking', 'BookingController');
    Route::get('/booking/search', 'BookingController@search');
    Route::get('/processbooking', 'BookingController@process');
    Route::get('/donebooking', 'BookingController@done');

    Route::resource('/transaction', 'TransactionController');
    Route::get('/transaction/invoice/{id}', 'TransactionController@invoice');

    Route::resource('/room', 'RoomController');
    Route::get('/room/search', 'RoomController@search');
    
    Route::resource('/datauser', 'DataUserController');
    Route::get('/datauser/search', 'DataUserController@search');

    Route::resource('/history', 'HistoryController');

    // logout
    Route::get('/logoutt', function(){
        Auth::logout();
        redirect('/');
    });
});

app/Models/Booking.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Booking extends Model
{
    use HasFactory;
    protected $table = 'bookings';
    protected $id = 'id';
    protected $fillable = [
        'id',
        'room',
        'data_user',
        'checkin',
        'checkout',
        'total',
        'status'
    ];
}

app/Http/Controllers/BookingController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Models\Room;
use App\Models\User;
use App\Models\Role;
use App\Models\Booking;
use App\Models\DataUser;
use App\Models\Transaction;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Requests\BookingRequest AS Valid;
use App\Repositories\BookingRepository AS Repo;
use App\Repositories\DataUserRepository AS RepoDataUser;
use App\Repositories\RoomRepository AS RepoRoom;
use App\Repositories\TransactionRepository AS RepoTransaction;

class BookingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    protected $user;

    public function __construct(User $user)
    {
        $this->middleware('auth');
        $this->user = $user;
    }

    public function index(RepoRoom $reporoom)
    {
        if(Gate::allows('isAdmin')){
            $role = Role::roleAdmin;
        }else if(Gate::allows('isUser')){
            $role = Role::roleUser;
        }else{
            return redirect()->action('HomeController@index')->with(['error' => 'Menu Booking tidak bisa ditampilkan !']);
        }
        
        $datas = $reporoom->get_all();
        return view('booking.index')
                ->with('datas', $datas)
                ->with('role', $role);
    }

    public function process(Repo $repository)
    {
        if(Gate::allows('isAdmin')){
            $role = Role::roleAdmin;
        }else if(Gate::allows('isUser')){
            return redirect()->action('HomeController@index')->with(['error' => 'Anda tidak bisa mengakses menu ini']);
        }else{
            return redirect()->action('HomeController@index')->with(['error' => 'Menu Booking tidak bisa ditampilkan !']);
        }

        $datas = $repository->get_data_process();

        return view('booking.process')
                ->with('datas', $datas)
                ->with('role', $role);
    }

    public function done(Repo $repository)
    {
        if(Gate::allows('isAdmin')){
            $role = Role::roleAdmin;
        }else if(Gate::allows('isUser')){
            return redirect()->action('HomeController@index')->with(['error' => 'Anda tidak bisa mengakses menu ini']);
        }else{
            return redirect()->action('HomeController@index')->with(['error' => 'Menu Booking tidak bisa ditampilkan !']);
        }

        $datas = $repository->get_data_done();

        return view('booking.done')
                ->with('datas', $datas)
                ->with('title', 'Edit')
                ->with('role', $role);
    }

    public function search()
    {
        return view('booking.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('booking.form')
                ->with('title', 'Tambah');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Valid $request, Repo $repository)
    {
        // validation
        $validated = $request->validated();
        
        // create
        if($repository->create($request->input()))
        {
            return redirect()->action('BookingController@index')->with(['success' => 'Data berhasil ditambahkan !']);
        }else{
            return redirect()->action('BookingController@index')->with(['error' => 'Data gagal ditambahkan !']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */

    public function show(RepoRoom $reporoom, RepoDataUser $repositoryUser, $booking)
    {
        if(Gate::allows('isAdmin')){
            $role = Role::roleAdmin;
            $customers = $repositoryUser->all();
        }else if(Gate::allows('isUser')){
            $role = Role::roleUser;
            $customers = $repositoryUser->all_by_user();
        }else{
            return redirect()->action('HomeController@index')->with(['error' => 'Menu Booking tidak bisa ditampilkan !']);
        }

        $room =$reporoom->show($booking);
        
        return view('booking.form')
                ->with('room', $room )
                ->with('customers', $customers )
                ->with('title', 'Tambah')
                ->with('url', 'booking')
                ->with('role', $role);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function edit(
        Repo $repository, RepoRoom $reporoom, RepoDataUser $repoDataUser,
        RepoTransaction $repotransaction, Booking $booking
        )
    {
        if(Gate::allows('isAdmin')){
            $role = Role::roleAdmin;
        }else if(Gate::allows('isUser')){
            return redirect()->action('HomeController@index')->with(['error' => 'Anda tidak bisa mengakses menu ini']);
        }else{
            return redirect()->action('HomeController@index')->with(['error' => 'Menu Booking tidak bisa ditampilkan !']);
        }

        $data = $repository->get_data_by_id($booking->id);
        $room = $reporoom->get_data_by_id($booking->room);
        $transaction = $repotransaction->get_data_by_booking($booking->id);
        $customer = $repoDataUser->get_data_by_id($booking->data_user);
        return view('booking.form')
                ->with('data', $data)
                ->with('room', $room)
                ->with('customer', $customer)
                ->with('transaction', $transaction)
                ->with('title', 'Edit')
                ->with('url', 'processbooking')
                ->with('role', $role);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Booking $booking)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function destroy(Booking $booking)
    {
        //
    }
}

resources/views/booking/done.blade.php
@extends('layouts.app')
@section('nav')
    @include('layouts.nav-'. $role)
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link" href="{{url('/booking')}}">Booking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url('/processbooking')}}">Process</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="#">Done</a>
                        </li>
                    </ul>
                    <div class="row m-3 d-flex justify-content-between">
                        <h4 class="mt-3"><strong>Done</strong></h4><br>
                    </div>
                    @if ($message = session('success'))
                        <div class="alert alert-success" role="alert">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                    @endif
                    @if ($message = session('error'))
                        <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                    @endif
                    @if ($message = session('warning'))
                        <div class="alert alert-warning" role="alert">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                    @endif
                    <div class="row ml-3">
                        <div class="col-md-12">
                        <form action="{{action('BookingController@search') }}" method="GET">
                            @csrf
                            <div class="form-group row">
                                <input type="text" class="form-control col-3 mr-3" name="cari" id="" placeholder="Cari">
                                <input class="form-group btn btn-sm btn-dark mr-2" type="submit" value="Search">
                                <input class="form-group btn btn-sm btn-light" type="submit" value="Reset">
                            </div>
                        </form>
                        </div>
                    </div>
                    <div class="container">
                        <div class="row center">
                            <table class="table w-100">
                                <thead class="bg-light text-center">
                                    <tr>
                                        <th scope="col">KODE</th>
                                        <th scope="col">CUSTOMER</th>
                                        <th scope="col">TIPE KAMAR</th>
                                        <th scope="col">CHECKIN</th>
                                        <th scope="col">CHECKOUT</th>
                                        <th scope="col">STATUS</th>
                                        <th scope="col">ACTION</th>
                                    </tr>
                                </thead>
                                <tbody class="text-center">
                                    <?php $i = $datas->firstItem(); ?>
                                    @forelse($datas as $data)
                                        <tr>
                                            <th>{{$data->kode}}</th>
                                            <th>{{$data->name}}</th>
                                            <th>{{$data->type_room}}</th>
                                            <th>{{$data->checkin}}</th>
                                            <th>{{$data->checkout}}</th>
                                            <th>{{$data->status}}</th>
                                            <th>
                                                <div class="btn-group" role="group" aria-label="Basic example">
                                                    <div>
                                                        <a href="{{route('booking.edit', ['booking'=> $data->kode]) }}" class="btn btn-sm btn-outline-dark">
                                                            <span data-feather="eye"></span>
                                                        </a>
                                                    </div>
                                                </div>
                                            </th>
                                        </tr>
                                    @empty
                                    <tr>
                                        <td colspan="7" class="text-center">
                                            No data found
                                        </td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/booking/example.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row m-3 d-flex justify-content-left">
                        <a href="{{ route('booking.index')}}" data-inline="true" class="btn btn-sm btn-dark" style="padding:10px; margin:4px;"><span data-feather="arrow-left">Add</span></a>
                        <h4 class="mt-3 pl-3"><strong>Tambah Booking</strong></h4><br>
                    </div>
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <!-- form -->
                    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                            <div class="p-6 bg-white border-b border-gray-200">
                                <div class="p-4 mb-4">
                                    @if($title == 'Edit')
                                        <form method="post" action="{{route('booking.update', ['booking'=> $data->id])}}" enctype="multipart/form-data">
                                        @method('PUT')
                                    @else
                                        <form method="post" action="{{route('booking.store')}}" enctype="multipart/form-data">
                                    @endif
                                        @csrf
                                        <input type="hidden" value="{{$data->id ?? ''}}" name="id">
                                        <!-- name -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Nama</label>
                                            <div class="col-sm-10">
                                                <input type="text" name="name" class="form-control" id="" placeholder="Enter Nama Room" value="{{$data->name ?? ''}}">
                                                @if ($errors->has('name'))
                                                    <span class="text-danger">{{ $errors->first('name') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <!-- Tipe Bed -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Tipe Bed</label>
                                            <div class="col-sm-10">
                                                <div class="col-sm-10">
                                                    <select class="form-control" name="type_bed" id="exampleFormControlSelect1">
                                                        <option value="">Enter Jenis Kamar</option>
                                                        <option value="">Standard</option>
                                                        <option value="">Superior</option>
                                                        <option value="">Deluxe</option>
                                                    </select>
                                                    @if ($errors->has('name'))
                                                        <span class="text-danger">{{ $errors->first('name') }}</span>
                                                    @endif
                                                </div>
                                                @if ($errors->has('type_bed'))
                                                    <span class="text-danger">{{ $errors->first('type_bed') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <!-- price -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Harga</label>
                                            <div class="col-sm-10">
                                                <input type="text" name="price" class="form-control" id="" placeholder="Enter Harga" value="{{$data->price ?? ''}}">
                                                @if ($errors->has('price'))
                                                    <span class="text-danger">{{ $errors->first('price') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <!-- Description  -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Deskripsi</label>
                                            <div class="col-sm-10">
                                                <input type="text" name="description" class="form-control" id="" placeholder="Enter Deskripsi" value="{{$data->description ?? ''}}">
                                                @if ($errors->has('description'))
                                                    <span class="text-danger">{{ $errors->first('description') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <!-- submit -->
                                        <div class="d-flex justify-content-end">
                                            <input class="btn btn-md btn-dark" type="submit" name="submit" value="Submit" style="padding:10px; margin:4px">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/booking/form.blade.php
@extends('layouts.app')
@section('nav')
    @include('layouts.nav-'. $role)
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row m-3 d-flex justify-content-left">
                        <a href="{{ url('/'. $url)}}" data-inline="true" class="btn btn-sm btn-dark" style="padding:10px; margin:4px;"><span data-feather="arrow-left">Back</span></a>
                        <h4 class="mt-3 pl-3"><strong>Booking</strong></h4><br>
                    </div>
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <!-- form -->
                    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                            <div class="p-6 bg-white border-b border-gray-200">
                                @if($title == 'Edit')
                                <form method="post" action="{{route('booking.update', ['booking'=> $data->id])}}" enctype="multipart/form-data">
                                @method('PUT')
                                @else
                                <form method="post" action="{{route('booking.store')}}">
                                @endif
                                    @csrf
                                    <div class="p-4 mb-4">
                                        <h5 class="mb-4">Data Kamar</h5>
                                        <input type="hidden" name="room" id="" value="{{$room->id}}">
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Tipe Kamar</strong></label>
                                            <div class="col-sm-10">
                                                <label for="">{{$room->type_room}}</label>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Tipe Kasur</strong></label>
                                            <div class="col-sm-10">
                                                <label for="">{{$room->description}}</label>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Harga</strong></label>
                                            <div class="col-sm-10">
                                                <input type="hidden" value="{{$room->price}}" name="price">
                                                <label for="">{{$room->price}}</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="p-4 mb-4">
                                        <h5 class="mb-4">Data Pemesan</h5>
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Nama</strong></label>
                                            <div class="col-sm-10">
                                                @if($title == 'Tambah')
                                                    <select class="form-control" name="data_user" id="exampleFormControlSelect1">
                                                        <option value="">Enter Data Pemesan</option>
                                                        @foreach($customers as $customer)
                                                            <option value="{{$customer->id}}" {{ ($data->data_user ?? old('data_user')) == $customer->id ? 'selected':'' }} > {{$customer->name}} </option>
                                                        @endforeach
                                                    </select>
                                                    <a class="ml-2" href="{{route('datauser.create')}}">Tambah</a>
                                                    @if ($errors->has('data_user'))
                                                        <span class="text-danger">{{ $errors->first('data_user') }}</span>
                                                    @endif
                                                @else
                                                    <label >{{$customer->name}}</label>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                    <div class="p-4 mb-4">
                                        <h5 class="mb-4">Data Booking</h5>
                                        <!-- checkin -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Checkin</label>
                                            <div class="col-sm-10">
                                                <input type="date" name="checkin" class="form-control" id="" placeholder="Enter Tanggal Chekin" value="{{$data->checkin ?? old('checkin')}}">
                                                @if ($errors->has('checkin'))
                                                    <span class="text-danger">{{ $errors->first('checkin') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <!-- checkout -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Checkout</label>
                                            <div class="col-sm-10">
                                                <input type="date" name="checkout" class="form-control" id="" placeholder="Enter Tanggal Chekout" value="{{$data->checkout ?? old('checkout')}}">
                                                @if ($errors->has('checkout'))
                                                    <span class="text-danger">{{ $errors->first('checkout') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <input type="hidden" name="status" class="form-control" id="" placeholder="{{$data->status ?? old('status')}}" value="Process" readonly>
                                    </div>
                                    @if($title == 'Edit')
                                    <div class="p-4 mb-4">
                                        <h5 class="mb-4">Data Transaksi</h5>
                                        
                                        <input type="hidden" value="{{$data->id ?? old('id')}}" name="id">
                                        <!-- total biaya -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Total Biaya</strong></label>
                                            <div class="col-sm-10">
                                                <label for="inputEmail3" class="col-sm-2 col-form-label">{{$transaction->total}}</label>
                                            </div>
                                        </div>
                                        <!-- status pembayaran -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Status Pembayaran</strong></label>
                                            <div class="col-sm-10">
                                                <label for="inputEmail3" class="col-sm-2 col-form-label">{{$transaction->status}}</label>
                                            </div>
                                        </div>
                                        <!-- bukti pembayaran -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Bukti Pembayaran</strong></label>
                                            <div class="col-sm-10">
                                                @if(!empty($transaction->file))
                                                    <img class="p-3" style="width:50%" src="{{$transaction->file ? \Illuminate\Support\Facades\Storage::url($transaction->file) : ''}}" alt="">
                                                @else
                                                    <label for="inputEmail3" class="col-sm-2 col-form-label">{{$transaction->status}}</label>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                    @else
                                    <div class="p-4" mb-4>
                                            <!-- submit -->
                                            <div class="d-flex justify-content-end">
                                            <input class="btn btn-md btn-success" type="submit" name="submit" value="Submit" style="padding:10px; margin:4px">
                                        </div>
                                    </div>
                                    @endif
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection