routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::middleware(['auth'])->group(function(){
    // home
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    // booking
    Route::resource('/booking', 'BookingController');
    Route::get('/booking/search', 'BookingController@search');
    Route::get('/processbooking', 'BookingController@process');
    Route::get('/donebooking', 'BookingController@done');

    Route::resource('/transaction', 'TransactionController');
    Route::get('/transaction/invoice/{id}', 'TransactionController@invoice');

    Route::resource('/room', 'RoomController');
    Route::get('/room/search', 'RoomController@search');
    
    Route::resource('/datauser', 'DataUserController');
    Route::get('/datauser/search', 'DataUserController@search');

    Route::resource('/history', 'HistoryController');

    // logout
    Route::get('/logoutt', function(){
        Auth::logout();
        redirect('/');
    });
});

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    use HasFactory;
    protected $table = 'rooms';
    protected $id = 'id';
    protected $fillable = [
        'id',
        'type_room',
        'type_bed',
        'total',
        'price',
        'description'
    ];
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Room;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Requests\RoomRequest AS Valid;
use App\Repositories\RoomRepository AS Repo;

class RoomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct(User $user)
    {
        $this->middleware('auth');
        $this->user = $user;
    }

    public function index(Repo $repository)
    {
        if(Gate::allows('isAdmin')){
            $role = Role::roleAdmin;
        }else{
            return redirect()->action('HomeController@index')->with(['error' => 'Menu Booking tidak bisa ditampilkan !']);
        }

        $datas = $repository->get_all();
        return view('room.index')
                ->with('datas', $datas);
    }

    // search
    public function search(Repo $repository, Request $request)
    {
        $key = trim($request->get('cari'));
        $datas = $repository->search($key);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('room.form')
                ->with('title', 'Tambah');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Valid $request, Repo $repository)
    {
        // validation
        $validated = $request->validated();

        // create
        if($repository->create($request->input()))
        {
            return redirect()->action('RoomController@index')->with(['success' => 'Data berhasil ditambahkan !']);
        }else{
            return redirect()->action('RoomController@index')->with(['error' => 'Data gagal ditambahkan !']);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function edit(Repo $repository, Room $room)
    {
        if(Gate::allows('isAdmin')){
            $role = Role::roleAdmin;
            $data = $repository->get_data_by_id($room->id);
        }else{
            return redirect()->action('HomeController@index')->with(['error' => 'Menu Booking tidak bisa ditampilkan !']);
        }

        if(!empty($data))
        {
            return view('room.form')
                    ->with('data', $data)
                    ->with('title', 'Edit');
        }else{
            return redirect()->action('RoomController@index')->with(['error' => 'Data tidak tersedia !']);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function update(Repo $repository, Valid $request, Room $room)
    {
        // validation
        $validated = $request->validated();
        
        // update
        if($repository->update($request->input()))
        {
            return redirect()->action('RoomController@index')->with(['success' => 'Data berhasil diupdate !']);
        }else{
            return redirect()->action('RoomController@index')->with(['error' => 'Data gagal diupdate !']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function destroy(Repo $repository, Room $room)
    {
        if($repository->delete($room->id))
        {
            return redirect()->action('RoomController@index')->with(['success' => 'Data berhasil dihapus !']);
        }else{
            return redirect()->action('RoomController@index')->with(['error' => 'Data gagal dihapus !']);
        }
    }
}

resources/views/room/form.blade.php
@extends('layouts.app')
@section('nav')
    @include('layouts.nav-Admin')
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row m-3 d-flex justify-content-between">
                        <div class="row">
                            <a href="{{ route('room.index')}}" data-inline="true" class="btn btn-sm btn-dark" style="padding:10px; margin:4px;"><span data-feather="arrow-left">Add</span></a>
                            <h4 class="mt-3 pl-3"><strong>{{$title}} Room</strong></h4><br>
                        </div>
                        <div class="row">
                            <a href="">Data Master / </a>
                            <a href="{{url('/room')}}">&nbsp Data Room / </a>
                            <p>&nbsp {{$title}} Room</p>
                        </div>
                    </div>
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <!-- form -->
                    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                            <div class="p-6 bg-white border-b border-gray-200">
                                <div class="p-4 mb-4">
                                    @if($title == 'Edit')
                                        <form method="post" action="{{route('room.update', ['room'=> $data->id])}}" enctype="multipart/form-data">
                                        @method('PUT')
                                    @else
                                        <form method="post" action="{{route('room.store')}}">
                                    @endif
                                        @csrf
                                        <input type="hidden" value="{{$data->id ?? old('id') }}" name="id">
                                        <!-- name -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Tipe Kamar</label>
                                            <div class="col-sm-10">
                                                <select class="form-control" name="type_room" id="exampleFormControlSelect1">
                                                    <option value="">Enter Tipe Kamar</option>
                                                    <option value="Standard" {{ ($data->type_room ?? old('type_room') ) == "Standard" ? 'selected':'' }}>Standard</option>
                                                    <option value="Superior" {{ ($data->type_room ?? old('type_room') ) == "Superior" ? 'selected':'' }}>Superior</option>
                                                    <option value="Deluxe" {{ ($data->type_room ?? old('type_room') ) == "Deluxe" ? 'selected':'' }}>Deluxe</option>
                                                </select>
                                                @if ($errors->has('type_room'))
                                                    <span class="text-danger">{{ $errors->first('type_room') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <!-- Tipe Bed -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Tipe Kasur</label>
                                            <div class="col-sm-10">
                                                <select class="form-control" name="type_bed" id="exampleFormControlSelect1">
                                                    <option value="">Enter Tipe Kasur</option>
                                                    <option value="Single" {{ ($data->type_bed ?? old('type_bed') ) == "Single" ? 'selected':'' }}>Single</option>
                                                    <option value="Queen" {{ ($data->type_bed ?? old('type_bed') ) == "Queen" ? 'selected':'' }}>Queen</option>
                                                    <option value="King" {{ ($data->type_bed ?? old('type_bed') ) == "King" ? 'selected':'' }}>King</option>
                                                </select>
                                                @if ($errors->has('type_bed'))
                                                    <span class="text-danger">{{ $errors->first('type_bed') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <!-- total kamar -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Total Kamar</label>
                                            <div class="col-sm-10">
                                                <input type="text" name="total" class="form-control" id="" placeholder="Enter Total Kamar" value="{{$data->total ?? old('total') }}">
                                                @if ($errors->has('total'))
                                                    <span class="text-danger">{{ $errors->first('total') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <!-- price -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Harga</label>
                                            <div class="col-sm-10">
                                                <input type="text" name="price" class="form-control" id="" placeholder="Enter Harga" value="{{$data->price ?? old('price') }}">
                                                @if ($errors->has('price'))
                                                    <span class="text-danger">{{ $errors->first('price') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <!-- Description  -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Deskripsi</label>
                                            <div class="col-sm-10">
                                                <input type="text" name="description" class="form-control" id="" placeholder="Enter Deskripsi" value="{{$data->description ?? old('description') }}">
                                                @if ($errors->has('description'))
                                                    <span class="text-danger">{{ $errors->first('description') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <!-- submit -->
                                        <div class="d-flex justify-content-end">
                                            <input class="btn btn-md btn-success" type="submit" name="submit" value="Submit" style="padding:10px; margin:4px">
                                        </div>
                                    </form>
                                </div>
                                <!-- <div class="p-4 mb-4">
                                    <table class="table w-100">
                                        <thead class="text-center">
                                            <tr>
                                                <th scope="col">NOMOR RUANG</th>
                                                <th scope="col">STATUS</th>
                                                <th scope="col">#</th>
                                            </tr>
                                        </thead>
                                        <tbody class="text-center">
                                            <tr>
                                                <th>201</th>
                                                <th>Available</th>
                                                <th>
                                                    <div class="btn-group" role="group" aria-label="Basic example">
                                                        <div>
                                                            <form action="#" method="POST">
                                                                @method('DELETE')
                                                                @csrf
                                                                <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Apakah anda yakin akan menghapus')" ><span data-feather="trash"></span></button>
                                                            </form>
                                                        </div>
                                                    </div>
                                                </th>
                                            </tr>
                                            <tr>
                                                <th><input class="form-control" type="text" placeholder="000"></th>
                                                <th>
                                                    <select class="form-control" name="type_bed" id="exampleFormControlSelect1">
                                                        <option value="">Available</option>
                                                        <option value="">Booked</option>
                                                    </select>
                                                </th>
                                                <th>
                                                    <div class="btn-group" role="group" aria-label="Basic example">
                                                        <div>
                                                            <a href="#" class="btn btn-sm btn-dark">
                                                                <span data-feather="plus"></span>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </th>
                                            </tr>
                                        </tbody>
                                    </table><br>
                                </div> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/room/index.blade.php
@extends('layouts.app')
@section('nav')
    @include('layouts.nav-Admin')
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row m-3 d-flex justify-content-between">
                        <h4 class="mt-3"><strong>Data Room</strong></h4><br>
                        <div class="row">
                            <a href="">Data Master / </a>
                            <p>&nbsp Data Room</p>
                        </div>
                    </div>
                    <div class="row m-3 d-flex justify-content-between">
                        <div class="col-md-10">
                            <form action="{{action('RoomController@search') }}" method="GET">
                                @csrf
                                <div class="form-group row">
                                    <input type="text" class="form-control col-3 mr-3" name="cari" id="" placeholder="Cari">
                                    <input class="form-group btn btn-sm btn-dark mr-2" type="submit" value="Search">
                                    <input class="form-group btn btn-sm btn-light" type="submit" value="Reset">
                                </div>
                            </form>
                        </div>
                        <div>
                            <a href="{{ route('room.create')}}" data-inline="true" class="btn btn-sm btn-dark" style="padding:10px; margin:4px;"><span data-feather="plus">Add</span></a>
                        </div>
                    </div>
                    @if ($message = session('success'))
                        <div class="alert alert-success" role="alert">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                    @endif
                    @if ($message = session('error'))
                        <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                    @endif
                    @if ($message = session('warning'))
                        <div class="alert alert-warning" role="alert">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                    @endif
                    <table class="table w-100">
                        <thead class="bg-light text-center">
                            <tr>
                                <th scope="col">NO</th>
                                <th scope="col">TIPE KAMAR</th>
                                <th scope="col">TIPE KASUR</th>
                                <th scope="col">TOTAL</th>
                                <th scope="col">HARGA</th>
                                <th scope="col">DESKRIPSI</th>
                                <th scope="col">ACTION</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            <?php $i = $datas->firstItem(); ?>
                            @forelse($datas as $data)
                            <tr>
                                <th>{{$i++}}</th>
                                <th>{{$data->type_room}}</th>
                                <th>{{$data->type_bed}}</th>
                                <th>{{$data->total}}</th>
                                <th>{{$data->price}}</th>
                                <th>{{$data->description}}</th>
                                <th>
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <div>
                                            <a href="{{route('room.edit', ['room'=> $data->id]) }}" class="btn btn-sm btn-success">
                                                <span data-feather="edit"></span>
                                            </a>
                                        </div>
                                        <div>
                                            <form action="{{action('RoomController@destroy', ['room'=> $data->id]) }}" method="POST">
                                                @method('DELETE')
                                                @csrf
                                                <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Apakah anda yakin akan menghapus')" ><span data-feather="trash"></span></button>
                                            </form>
                                        </div>
                                    </div>
                                </th>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="6" class="text-center">
                                    No data found
                                </td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                    {{ $datas->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection