routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::middleware(['auth'])->group(function(){
    // home
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    // booking
    Route::resource('/booking', 'BookingController');
    Route::get('/booking/search', 'BookingController@search');
    Route::get('/processbooking', 'BookingController@process');
    Route::get('/donebooking', 'BookingController@done');

    Route::resource('/transaction', 'TransactionController');
    Route::get('/transaction/invoice/{id}', 'TransactionController@invoice');

    Route::resource('/room', 'RoomController');
    Route::get('/room/search', 'RoomController@search');
    
    Route::resource('/datauser', 'DataUserController');
    Route::get('/datauser/search', 'DataUserController@search');

    Route::resource('/history', 'HistoryController');

    // logout
    Route::get('/logoutt', function(){
        Auth::logout();
        redirect('/');
    });
});

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use PDF;
use Auth;
use App\Models\Transaction;
use App\Models\Booking;
use App\Models\User;
use App\Models\Role;
use App\Models\DataUser;
use App\Models\Room;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Repositories\TransactionRepository AS Repo;
use App\Repositories\BookingRepository AS RepoBooking;
use App\Repositories\DataUserRepository AS RepoDataUser;
use App\Repositories\RoomRepository AS RepoRoom;

class TransactionController extends Controller
{
    public function __construct(User $user)
    {
        $this->middleware('auth');
        $this->user = $user;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Repo $repository)
    {
        if(Gate::allows('isAdmin')){
            $role = Role::roleAdmin;
            $datas = $repository->get_all();
        }else if(Gate::allows('isUser')){
            $role = Role::roleUser;
            $datas = $repository->get_all_by_user();
        }else{
            return redirect()->action('HomeController@index')->with(['error' => 'Menu Transaksi tidak bisa ditampilkan !']);
        }

        return view('transaction.index')
                ->with('datas', $datas)
                ->with('role', $role);
    }

    // search
    public function search()
    {
        return view('transaction.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Repo $repository, RepoBooking $repobooking,
        RepoDataUser $repodatauser, RepoRoom $reporoom, Transaction $transaction
        )
    {
        if(Gate::allows('isAdmin')){
            $role = Role::roleAdmin;
        }else if(Gate::allows('isUser')){
            $role = Role::roleUser;
        }else{
            return redirect()->action('HomeController@index')->with(['error' => 'Menu Transaksi tidak bisa ditampilkan !']);
        }

        $data = $repository->get_data_by_id($transaction->id);
        if(!empty($data))
        {
            $bookings = $repobooking->get_data_by_id($transaction->booking);
            $customers = $repodatauser->get_data_by_id($bookings->data_user);
            $rooms = $reporoom->get_data_by_id($bookings->room);
            return view('transaction.form')
                    ->with('data', $data)
                    ->with('booking', $bookings)
                    ->with('customer', $customers)
                    ->with('room', $rooms)
                    ->with('title', 'Edit')
                    ->with('role', $role);
        }else{
            return redirect()->action('TransactionController@index')->with(['error' => 'Data tidak tersedia !']);
        }
    }

    public function invoice(Repo $repository, RepoBooking $repobooking,
        RepoDataUser $repodatauser, RepoRoom $reporoom, $transaction)
    {
        $data = $repository->get_data_by_id($transaction);
        if(!empty($data))
        {

            $booking = $repobooking->get_data_by_id($data->booking);
            $customer = $repodatauser->get_data_by_id($booking->data_user);
            $room = $reporoom->get_data_by_id($booking->room);

            $pdf = PDF::loadview('transaction.invoice', 
                    [
                        'data' => $data,
                        'booking' => $booking,
                        'customer' => $customer,
                        'room' => $room
                    ]
            );
            return $pdf->stream('invoice-pembayaran.pdf');
            
        }else{
            return redirect()->action('TransactionController@edit'. ['id' => $transaction])->with(['error' => 'Data tidak tersedia !']);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Repo $repository,
        RepoBooking $repobooking, Transaction $transaction)
    {
        if (!is_null($request->file('bukti'))){
            $transaction->file = $request->file('bukti')->store('public');
            $transaction->save();
        }

        if($update = $repository->update($transaction->id, $request->input()))
        {
            if($update->status == 'Lunas'){
                $repobooking->update_status_done($transaction->booking);
            }elseif($update->status == 'Cancel'){
                $repobooking->update_status_cancel($transaction->booking);
            }
            
            return redirect()->action('TransactionController@index')->with(['success' => 'Data berhasil diupdate !']);
        }else{
            return redirect()->action('TransactionController@index')->with(['error' => 'Data gagal diupdate !']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        //
    }

}

resources/views/transaction/form.blade.php
@extends('layouts.app')
@section('nav')
    @include('layouts.nav-'. $role)
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row m-3 d-flex justify-content-between">
                        <div class="row">
                            <a href="{{ route('transaction.index')}}" data-inline="true" class="btn btn-sm btn-dark" style="padding:10px; margin:4px;"><span data-feather="arrow-left">Add</span></a>
                            <h4 class="mt-3 pl-3"><strong>Transaksi</strong></h4><br>
                        </div>
                        @if($data->status == 'Lunas')
                            <a href="{{ url('/transaction/invoice', ['transaction'=> $data->id])}}" target="_blank" data-inline="true" class="btn btn-sm btn-dark" style="padding:10px; margin:4px;"><span data-feather="download">Download</span></a>
                        @else
                            <a href="{{ url('/transaction/invoice', ['transaction'=> $data->id])}}" target="_blank" data-inline="true" class="btn btn-sm btn-dark" style="padding:10px; margin:4px;"><span data-feather="download">Download</span></a>
                        @endif
                    </div>
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <!-- form -->
                    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                            <div class="p-6 bg-white border-b border-gray-200">
                                @if($title == 'Edit')
                                <form method="post" action="{{route('transaction.update', ['transaction'=> $data->id])}}" enctype="multipart/form-data">
                                @method('PUT')
                                @else
                                <form method="post" action="{{route('transaction.store')}}">
                                @endif
                                    @csrf
                                    <div class="p-4 mb-4">
                                        <h5 class="mb-4">Data Kamar</h5>
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Tipe Kamar</strong></label>
                                            <div class="col-sm-10">
                                                <label for="">{{$room->type_room}}</label>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Tipe Kasur</strong></label>
                                            <div class="col-sm-10">
                                                <label for="">{{$room->description}}</label>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Harga</strong></label>
                                            <div class="col-sm-10">
                                                <label for="">{{$room->price}}</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="p-4 mb-4">
                                        <h5 class="mb-4">Data Customer</h5>
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Nama</strong></label>
                                            <div class="col-sm-10">
                                                <label for="">{{$customer->name}}</label>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Email</strong></label>
                                            <div class="col-sm-10">
                                                <label for="">{{$customer->email}}</label>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Nomor Tlf</strong></label>
                                            <div class="col-sm-10">
                                                <label for="">{{$customer->phone}}</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="p-4 mb-4">
                                        <h5 class="mb-4">Data Booking</h5>
                                        <!-- checkin -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Checkin</label>
                                            <div class="col-sm-10">
                                                <div class="col-sm-10">
                                                    <label for="">{{$booking->checkin}}</label>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- checkout -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Checkout</label>
                                            <div class="col-sm-10">
                                                <div class="col-sm-10">
                                                    <label for="">{{$booking->checkout}}</label>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- total -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Total</label>
                                            <div class="col-sm-10">
                                                <div class="col-sm-10">
                                                    <label for="">{{$booking->total}}</label>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- Status -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Status Booking</label>
                                            <div class="col-sm-10">
                                                <div class="col-sm-10">
                                                    <label for="">{{$booking->status}}</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- status pembayaran -->
                                    <div class="p-4 mb-4">
                                        <h5 class="mb-4">Data Transaksi</h5>
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Total Biaya</strong></label>
                                            <div class="col-sm-10">
                                                <label for="inputEmail3" class="col-sm-2 col-form-label">{{$data->total}}</label>
                                            </div>
                                        </div>
                                        @if($role == 'Admin')
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Status</strong></label>
                                            <div class="col-sm-10">
                                                <select class="form-control" name="status" id="exampleFormControlSelect1">
                                                    <option value="">Enter Status</option>
                                                    <option value="Pending" {{ ($data->status ?? '') == "Pending" ? 'selected':'' }} > Pending </option>
                                                    <option value="Process" {{ ($data->status ?? '') == "Process" ? 'selected':'' }} > Process </option>
                                                    <option value="Lunas" {{ ($data->status ?? '') == "Lunas" ? 'selected':'' }} > Lunas </option>
                                                    <option value="Cancel" {{ ($data->status ?? '') == "Cancel" ? 'selected':'' }} > Cancel </option>
                                                </select>
                                            </div>
                                        </div>
                                        @else
                                            <input class="form-group" name="status" type="hidden" value="Process">
                                        @endif
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label"><strong>Bukti Pembayaran</strong></label>
                                            <div class="col-sm-10">
                                                @if(!empty($data->file))
                                                    <img class="p-3" style="width:50%" src="{{$data->file ? \Illuminate\Support\Facades\Storage::url($data->file) : ''}}" alt="">
                                                @endif
                                                <input class="form-group" name="bukti" type="file" id="file">
                                                @if($role == 'User' && $data->status != 'Lunas')
                                                
                                                @endif
                                            </div>
                                        </div>
                                        <!-- submit -->
                                        @if($data->status == 'Lunas')
                                            
                                        @else
                                        <div class="d-flex justify-content-end">
                                            <input class="btn btn-md btn-success" type="submit" name="submit" value="Submit" style="padding:10px; margin:4px">
                                        </div>
                                        @endif
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/transaction/index.blade.php
@extends('layouts.app')
@section('nav')
    @include('layouts.nav-'. $role)
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row m-3 d-flex justify-content-between">
                        <h4 class="mt-3"><strong>Transaksi</strong></h4><br>
                    </div>
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="row ml-3">
                        <div class="col-md-12">
                        <form action="{{action('RoomController@search') }}" method="GET">
                            @csrf
                            <div class="form-group row">
                                <input type="text" class="form-control col-3 mr-3" name="cari" id="" placeholder="Cari">
                                <input class="form-group btn btn-sm btn-dark mr-2" type="submit" value="Search">
                                <input class="form-group btn btn-sm btn-light" type="submit" value="Reset">
                            </div>
                        </form>
                        </div>
                    </div>
                    @if ($message = session('success'))
                        <div class="alert alert-success" role="alert">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                    @endif
                    @if ($message = session('error'))
                        <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                    @endif
                    @if ($message = session('warning'))
                        <div class="alert alert-warning" role="alert">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                    @endif
                    <table class="table w-100">
                        <thead class="bg-light text-center">
                            <tr>
                                <th scope="col">KODE TRANSAKSI</th>
                                <th scope="col">KODE BOOKING</th>
                                <th scope="col">TOTAL</th>
                                <th scope="col">STATUS</th>
                                <th scope="col">ACTION</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            <?php $i = $datas->firstItem(); ?>
                            @forelse($datas as $data)
                            <tr>
                                <th>{{$data->id}}</th>
                                <th>{{$data->booking}}</th>
                                <th>
                                    {{$data->total}}
                                </th>
                                <th>
                                    {{$data->status}}
                                </th>
                                <th>
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <div>
                                        <a href="{{route('transaction.edit', ['transaction'=> $data->id]) }}" class="btn btn-sm btn-success">
                                                <span data-feather="edit"></span>
                                            </a>
                                        </div>
                                    </div>
                                </th>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="6" class="text-center">
                                    No data found
                                </td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                    {{ $datas->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/transaction/invoice.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Invoice</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <style>
            .clearfix:after {
            content: "";
            display: table;
            clear: both;
            }

            a {
            color: #5D6975;
            text-decoration: underline;
            }

            body {
            position: relative;
            width: 21cm;  
            height: 29.7cm; 
            margin: 0 auto; 
            color: #001028;
            background: #FFFFFF; 
            font-family: Arial, sans-serif; 
            font-size: 12px; 
            font-family: Arial;
            }

            header {
            padding: 10px 0;
            margin-bottom: 30px;
            }

            #logo {
            text-align: center;
            margin-bottom: 10px;
            }

            #logo img {
            width: 90px;
            }

            h1 {
            border-top: 1px solid  #5D6975;
            border-bottom: 1px solid  #5D6975;
            color: #5D6975;
            font-size: 2.4em;
            line-height: 1.4em;
            font-weight: normal;
            text-align: center;
            margin: 0 0 20px 0;
            background: url(dimension.png);
            }

            #project {
            float: left;
            }

            #project span {
            color: #5D6975;
            text-align: right;
            width: 52px;
            margin-right: 10px;
            display: inline-block;
            font-size: 0.8em;
            }

            #company {
            float: right;
            text-align: right;
            }

            #project div,
            #company div {
            white-space: nowrap;        
            }

            table {
            width: 100%;
            border-collapse: collapse;
            border-spacing: 0;
            margin-bottom: 20px;
            }

            table tr:nth-child(2n-1) td {
            background: #F5F5F5;
            }

            table th,
            table td {
            text-align: center;
            }

            table th {
            padding: 5px 20px;
            color: #5D6975;
            border-bottom: 1px solid #C1CED9;
            white-space: nowrap;        
            font-weight: normal;
            }

            table .service,
            table .desc {
            text-align: left;
            }

            table td {
            padding: 20px;
            text-align: right;
            }

            table td.service,
            table td.desc {
            vertical-align: top;
            }

            table td.unit,
            table td.qty,
            table td.total {
            font-size: 1.2em;
            }

            table td.grand {
            border-top: 1px solid #5D6975;;
            }

            #notices .notice {
            color: #5D6975;
            font-size: 1.2em;
            }

            footer {
            color: #5D6975;
            width: 100%;
            height: 30px;
            position: absolute;
            bottom: 0;
            border-top: 1px solid #C1CED9;
            padding: 8px 0;
            text-align: center;
            }
        </style>
    </head>
    <body>
        <header class="clearfix">
        <div id="logo">
            <img class="mb-4" src="https://dansmultipro.com/wp-content/uploads/2020/03/logo_web_header-810x180-1.png" alt="" width="50%">
        </div>
        <h1>INVOICE #{{$data->id}}</h1>
        <div class="row">
            <div id="project">
                <div><span>CUSTOMER</span> {{$customer->name}}</div>
                <div><span>EMAIL</span> <a href="mailto:john@example.com">{{$customer->email}}</a></div>
                <div><span>PHONE</span> {{$customer->phone}}</div>
                <div><span>DUE DATE</span> {{$booking->checkout}}</div>
            </div>
        </div>
        </header>
        <main>
        <table class="table" style="width: 700px">
            <thead class="text-center">
                <tr>
                    <th class="service">SERVICE</th>
                    <th class="desc">DESCRIPTION</th>
                    <th>TOTAL</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="service">
                        <strong>{{$room->type_room}}</strong><br>
                        <span>{{$room->type_bed}}</span>
                    </td>
                    <td class="desc">
                        {{$room->description}} <br>
                        {{$booking->checkin}} - {{$booking->checkout}} <br>
                        {{$booking->total}} Hari
                    </td>
                    <td class="unit">Rp. {{$data->total}}</td>
                </tr>
                <tr>
                    <td colspan="2">SUBTOTAL</td>
                    <td class="total">Rp. {{$data->total}}</td>
                </tr>
                <tr>
                    <td colspan="2" class="grand total">GRAND TOTAL</td>
                    <td class="grand total">Rp. {{$data->total}}</td>
                </tr>
            </tbody>
        </table>
        <div id="notices">
            <div>NOTICE:</div>
            <div class="notice">A finance charge of 1.5% will be made on unpaid balances after 30 days.</div>
        </div>
        </main>
        <footer>
        Invoice was created on a computer and is valid without the signature and seal.
        </footer>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>