routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::middleware(['auth'])->group(function(){
    // home
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    // booking
    Route::resource('/booking', 'BookingController');
    Route::get('/booking/search', 'BookingController@search');
    Route::get('/processbooking', 'BookingController@process');
    Route::get('/donebooking', 'BookingController@done');

    Route::resource('/transaction', 'TransactionController');
    Route::get('/transaction/invoice/{id}', 'TransactionController@invoice');

    Route::resource('/room', 'RoomController');
    Route::get('/room/search', 'RoomController@search');
    
    Route::resource('/datauser', 'DataUserController');
    Route::get('/datauser/search', 'DataUserController@search');

    Route::resource('/history', 'HistoryController');

    // logout
    Route::get('/logoutt', function(){
        Auth::logout();
        redirect('/');
    });
});

app/Models/DataUser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DataUser extends Model
{
    use HasFactory;
    protected $table = 'data_users';
    protected $id = 'id';
    protected $fillable = [
        'id',
        'name',
        'birth_date',
        'phone',
        'email',
        'user_id'
    ];
}

app/Http/Controllers/DataUserController.php
<?php

namespace App\Http\Controllers;

use Auth;
use Session;
use App\Models\User;
use App\Models\Role;
use App\Models\DataUser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use App\Http\Requests\DataUserRequest AS Valid;
use App\Repositories\DataUserRepository AS Repo;

class DataUserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Repo $repository)
    {
        if(Gate::allows('isAdmin')){
            $role = Role::roleAdmin;
            $datas = $repository->get_all();
        }else if(Gate::allows('isUser')){
            $role = Role::roleUser;
            $datas = $repository->get_all_by_user();
        }else{
            return redirect()->action('HomeController@index')->with(['error' => 'Menu Booking tidak bisa ditampilkan !']);
        }
        return view('data_user.index')
                ->with('datas', $datas)
                ->with('role', $role);
    }

    public function search(Request $request)
    {
        $key = trim($request->get('cari'));
        $datas = $repository->search($key);
        return view('data_user.index')
                ->with('datas', $datas);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('data_user.form')
                ->with('title', 'Tambah');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Valid $request, Repo $repository)
    {
        // validation
        $validated = $request->validated();

        // create
        if($repository->create($request->input()))
        {
            return redirect()->action('DataUserController@index')->with(['success' => 'Data berhasil ditambahkan !']);
        }else{
            return redirect()->action('DataUserController@index')->with(['error' => 'Data gagal ditambahkan !']);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\DataUser  $dataUser
     * @return \Illuminate\Http\Response
     */
    public function edit(Repo $repository, DataUser $datauser)
    {
        if(Gate::allows('isAdmin')){
            $role = Role::roleAdmin;
            $data = $repository->get_data_by_id($datauser->id);
        }elseif(Gate::allows('isUser')){
            $role = Role::roleUser;
            $data = $repository->get_data_by_id_user($datauser->id);
        }else{
            return redirect()->action('HomeController@index')->with(['error' => 'Menu Data User tidak bisa ditampilkan !']);
        }
        
        if(!empty($data))
        {
            return view('data_user.form')
                ->with('data', $data)
                ->with('title', 'Edit');
        }else{
            return redirect()->action('DataUserController@index')->with(['error' => 'Data tidak tersedia !']);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\DataUser  $dataUser
     * @return \Illuminate\Http\Response
     */
    public function update(Valid $request, Repo $repository, DataUser $datauser)
    {
        // validation
        $validated = $request->validated();
        
        // update
        if($repository->update($request->input()))
        {
            return redirect()->action('DataUserController@index')->with(['success' => 'Data berhasil diupdate !']);
        }else{
            return redirect()->action('DataUserController@index')->with(['error' => 'Data gagal diupdate !']);
        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\DataUser  $dataUser
     * @return \Illuminate\Http\Response
     */
    public function destroy(DataUser $datauser, Repo $repository)
    {
        if($repository->delete($datauser->id))
        {
            return redirect()->action('DataUserController@index')->with(['success' => 'Data berhasil dihapus !']);
        }else{
            return redirect()->action('DataUserController@index')->with(['error' => 'Data gagal dihapus !']);
        }
    }
}

resources/views/data_user/form.blade.php
@extends('layouts.app')
@section('nav')
    @include('layouts.nav-Admin')
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row m-3 d-flex justify-content-between">
                        <div class="row">
                            <a href="{{ route('datauser.index')}}" data-inline="true" class="btn btn-sm btn-dark" style="padding:10px; margin:4px;"><span data-feather="arrow-left">Add</span></a>
                            <h4 class="mt-3 pl-3"><strong>{{$title}} Pemesan</strong></h4><br>
                        </div>
                        <div class="row">
                            <a href="">Data Master / </a>
                            <a href="{{url('datauser')}}">&nbsp Data Pemesan / </a>
                            <p>&nbsp {{$title}} </p>
                        </div>
                    </div>
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <!-- form -->
                    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                            <div class="p-6 bg-white border-b border-gray-200">
                                <div class="p-4 mb-4">
                                    @if($title == 'Edit')
                                        <form method="post" action="{{route('datauser.update', ['datauser'=> $data->id])}}" enctype="multipart/form-data">
                                        @method('PUT')
                                    @else
                                        <form method="post" action="{{route('datauser.store')}}">
                                    @endif
                                        @csrf
                                        <input type="hidden" value="{{$data->id ?? ''}}" name="id">
                                        <!-- name -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Nama</label>
                                            <div class="col-sm-10">
                                                <input type="text" name="name" class="form-control" id="" placeholder="Enter Nama" value="{{$data->name ?? old('name')}}">
                                                @if ($errors->has('name'))
                                                    <span class="text-danger">{{ $errors->first('name') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <!-- TTL -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Tanggal Lahir</label>
                                            <div class="col-sm-10">
                                                <input type="date" name="birth_date" class="form-control" id="" placeholder="Enter Tanggal Lahir" value="{{$data->birth_date ?? old('birth_date')}}">
                                                @if ($errors->has('birth_date'))
                                                    <span class="text-danger">{{ $errors->first('birth_date') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <!-- email -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
                                            <div class="col-sm-10">
                                                <input type="email" name="email" class="form-control" id="" placeholder="Enter Email" value="{{$data->email ?? old('email')}}">
                                                @if ($errors->has('email'))
                                                    <span class="text-danger">{{ $errors->first('email') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <!-- phone -->
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">Nomor Telefon</label>
                                            <div class="col-sm-10">
                                                <input type="number" name="phone" class="form-control" id="" placeholder="Enter Nomor Telefon" value="{{$data->phone ?? old('phone')}}">
                                                @if ($errors->has('phone'))
                                                    <span class="text-danger">{{ $errors->first('phone') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <!-- submit -->
                                        <div class="d-flex justify-content-end">
                                            <input class="btn btn-md btn-success" type="submit" name="submit" value="Submit" style="padding:10px; margin:4px">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/data_user/index.blade.php
@extends('layouts.app')
@section('nav')
    @include('layouts.nav-'. $role)
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row m-3 d-flex justify-content-between">
                        <h4 class="mt-3"><strong>Data Pemesan</strong></h4><br>
                        <div class="row">
                            <a href="">Data Master / </a>
                            <p>&nbsp Data User</p>
                        </div>
                    </div>
                    <div class="row m-3 d-flex justify-content-between">
                        <div class="col-md-10">
                            <form action="{{ action('DataUserController@search') }}" method="GET">
                                @csrf
                                <div class="form-group row">
                                    <input type="text" class="form-control col-3 mr-3" name="cari" id="" placeholder="Cari">
                                    <input class="form-group btn btn-sm btn-dark mr-2" type="submit" value="Search">
                                    <input class="form-group btn btn-sm btn-light" type="submit" value="Reset">
                                </div>
                            </form>
                        </div>
                        <div>
                            <a href="{{ route('datauser.create')}}" data-inline="true" class="btn btn-sm btn-dark" style="padding:10px; margin:4px;"><span data-feather="plus">Add</span></a>
                        </div>
                    </div>
                    <div class="row ml-3">
                        
                    </div>
                    @if ($message = session('success'))
                        <div class="alert alert-success" role="alert">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                    @endif
                    @if ($message = session('error'))
                        <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                    @endif
                    @if ($message = session('warning'))
                        <div class="alert alert-warning" role="alert">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                    @endif
                    <table class="table w-100">
                        <thead class="bg-light text-center">
                            <tr>
                                <th scope="col">NO</th>
                                <th scope="col">NAMA</th>
                                <th scope="col">EMAIL</th>
                                <th scope="col">NO. TLP</th>
                                <th scope="col">ACTION</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            <?php $i = $datas->firstItem(); ?>
                            @forelse($datas as $data)
                                <tr>
                                    <th>{{$i++}}.</th>
                                    <th>{{$data->name}}</th>
                                    <th>{{$data->email}}</th>
                                    <th>{{$data->phone}}</th>
                                    <th>
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                            <div>
                                                <a href="{{route('datauser.edit', ['datauser'=> $data->id]) }}" class="btn btn-sm btn-success">
                                                    <span data-feather="edit"></span>
                                                </a>
                                            </div>
                                            <div>
                                                <form action="{{action('DataUserController@destroy', ['datauser'=> $data->id]) }}" method="POST">
                                                    @method('DELETE')
                                                    @csrf
                                                    <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Apakah anda yakin akan menghapus')" ><span data-feather="trash"></span></button>
                                                </form>
                                            </div>
                                        </div>
                                    </th>
                                </tr>
                            @empty
                            <tr>
                                <td colspan="6" class="text-center">
                                    No data found
                                </td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                    {{ $datas->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection